### ISSUE TITLE
ddynamic_reconfiguration

### ISSUE THREAD

**Issue by nrpr161293** [kehanXue/CeleX5-ROS#1]
Hello, can you please tell me where do you find the ddynamic_reconfigure package? I'm trying to build your code and I'm getting this error:
![image](https://user-images.githubusercontent.com/71510928/95971555-47618500-0e09-11eb-98f8-5dc13a060b8f.png)

**Comment by kehanXue** [comment]
Please use apt to install it. For example, just `sudo apt install ros-melodic-ddynamic-reconfigure` if you use Ubuntu 18.04 and ROS melodic.
