### ISSUE TITLE
ROSBAG

### ISSUE THREAD

**Issue by nrpr161293** [kehanXue/CeleX5-ROS#2]
Hi,

I'm trying to save the binary_img topic to the rosbag file, and when I play the rosbag it says that I have no messages to play on specified topic.

Do you know why?

**Comment by kehanXue** [comment]
Can you get the image when you are running the node? You can use `rqt_image_view` to check it. 

If there is no image display, please have a look at the [Q&A](https://github.com/kehanXue/CeleX5-ROS#qa).

**Comment by nrpr161293** [comment]
yes, I can see the binary_img using:
image_view image_view image:=/celex5_mipi/display/binary_img/raw_image
But doesn't save it on the bag file.

**Comment by kehanXue** [comment]
Did you try with `rosbag record /celex5_mipi/display/binary_img/raw_image`?

**Comment by nrpr161293** [comment]
My mistake I used:
rosbag record --duration=10 -O zimbre.bag /celex5_mipi/display/binary_img/image_raw
instead of this:
rosbag record --duration=10 -O zimbre.bag /celex5_mipi/display/binary_img/raw_image

Thank you

**Comment by kehanXue** [comment]
No thanks~
