### ISSUE TITLE
celex5_events

### ISSUE THREAD

**Issue by nrpr161293** [kehanXue/CeleX5-ROS#3]
Hi,

I'm trying to get information about the /celex5_mipi/events topic but for some reason, I can get that info, the following error appear:
![celex_events](https://user-images.githubusercontent.com/71510928/97452591-cf2cb080-192c-11eb-8620-190350153da5.png)

Can you please help me?

**Comment by kehanXue** [comment]
You just only need to source the setup.bash before you echo.

**Comment by nrpr161293** [comment]
But if I'm trying to do the same for topic /cepex5_mipi/imu it works. Just the /celex5_mipi/events doesn't work for some reason

**Comment by kehanXue** [comment]
The /cepex5_mipi/imu works because it's from ROS stand message type: sensor_msgs/Imu, so you don't need to source manully.

**Comment by nrpr161293** [comment]
You are absolutely right, my bad. Thank you!

**Comment by kehanXue** [comment]
No thanks.
