### ISSUE TITLE
  celex5_ros.h:No such file or directory

### ISSUE THREAD

**Issue by DavidNemn** [kehanXue/CeleX5-ROS#4]
when i try to use “catkin_make”,When I try to use the header file in another package, after catkin_make,the screen shows “ celex5_ros.h:No such file or directory”
could you help me？
I had add  depend in the packag.xml

**Comment by DavidNemn** [comment]
I had solved my problem
head files change to “celex5_msgs/Event.h”

**Comment by kehanXue** [comment]
Ok
