### ISSUE TITLE
Stereo camera supported

### ISSUE THREAD

**Issue by robin-shaun** [kehanXue/CeleX5-ROS#5]
Hi, is there any plan to support stereo event camera?

**Comment by kehanXue** [comment]
Sorry, I have no time recently, so I have no plans in the near future.

If you want to modify it to support multi cameras recently, I can provide some suggestions. You can have a look at the codes in celex_sdk which open camera through the `idVendor` and `idProduct` identifiers. Maybe you can add more identifiers to distinguish more different cameras.

**Comment by robin-shaun** [comment]
Ok,thanks a lot

**Comment by robin-shaun** [comment]
idVendor and idProduct are the same for different cameras. We can modify from this SDK [https://github.com/CelePixel/CeleX5-MIPI-Stereo](https://github.com/CelePixel/CeleX5-MIPI-Stereo)

**Comment by kehanXue** [comment]
Okay, I will have a look at it in my spare time.
