### ISSUE TITLE
Denoised image

### ISSUE THREAD

**Issue by robin-shaun** [kehanXue/CeleX5-ROS#6]
Hello, I find that the published denoised image(up) is the same as the published raw image(down).
![image](https://user-images.githubusercontent.com/20561850/117909699-4e079a80-b30d-11eb-8364-ee7dd210e8eb.png)

**Comment by kehanXue** [comment]
Emm, are you sure the denoised image is as the same as raw image? The denosied image looks like the [pic](https://github.com/kehanXue/CeleX5-ROS/blob/master/assets/Screenshot%20from%202020-01-22%2021-16-52.png)'s left-down image. Please check the parameters and the image topic are correct. Now I have none celeX5 camera so I coundn't check it. I will also check this problem if I get a celex5 canera in the future.

**Comment by robin-shaun** [comment]
Ok, thanks a lot
