### ISSUE TITLE
关于raw_image的类型

### ISSUE THREAD

**Issue by mosfe** [kehanXue/CeleX5-ROS#8]
您好，我按照您的提示成功地完成了运行。但是在topic上遇到了一些问题，比如您的演示图片中出现了彩色的光流，即colored_optical_image，但是我的话题中是没有的，还有一些比如superimposed_img、optical_flow_direction_img这些有什么区别呢，在官方文档中并没有看到，诚盼您的解答，谢谢！

**Comment by mosfe** [comment]
您好，以上问题已经解决啦。还有一些问题想请教一下：1.能否关闭loop3只是循环两个模式呢 2.在循环模式下full_frame很卡，这是什么问题呢 3.关于rqt_reconfigure的配置，是修改完立刻生效吗，进行了改动但在rviz中并没有看到明显的变化。

**Comment by mosfe** [comment]
您好，经过测试，只有在不循环的时候，通过 rviz看到的视频是不卡的，一旦进入循环模式，就会变得很卡。还有rqt_reconfigure的配置问题，这个是可以实时生效的，是我没有注意到。所以还剩下1和2两个问题，不知道博主现在还在做吗，希望交流一下。

**Comment by kehanXue** [comment]
变得很卡，是因为帧率变低了吗，ros topic hz看一下发布频率是否在预期？

**Comment by mosfe** [comment]
您好，经过查看帧率没有降低，循环模式下和固定模式下均为60，但是切换到循环模式下就会变得很卡，不知道您有没有试过

**Comment by kehanXue** [comment]
帧率没有降低，可能是Celex自身的问题？看看输出相关frame的一些参数。有些太久远了，记不太清楚了😢

**Comment by mosfe** [comment]
非常感谢您的回复！请问您现在还在进行这方面的相关研究吗，本人刚刚入门这个方向，希望可以深入交流一下

**Comment by kehanXue** [comment]
可以加我微信Kehanxxxxxxx
